{% set name = "gsoap" %}
{% set version = "2.8.95" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/gsoap2/gsoap-{{ version.split('.')[0] }}.{{ version.split('.')[1] }}/gsoap_{{ version }}.zip
  sha256: fe07aa152cd946ef8ebd3f87653f14c1d38efe7c6e6fce8c6f773c4814f79baf

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - bison
    - flex
    - gawk  # [unix]
    - make
  host:
    - openssl
    - zlib

test:
  commands:
    - soapcpp2 -h

about:
  home: https://www.genivia.com/
  license: GPL-2.0
  license_family: GPL
  license_file: GPLv2_license.txt
  summary: 'The most advanced C/C++ autocoding tools for XML Web service APIs and other XML applications'

  description: |
     gSOAP is the top-rated agile development framework for C/C++ Web service
     APIs and XML. Join our rapidly growing world-wide customer base with
     over a million downloads. Start expediting the development of your
     products to meet the latest industry standards for XML, XML Web services,
     WSDL and SOAP, REST, JSON, WS-Security, WS-Trust with SAML,
     WS-ReliableMessaging, WS-Discovery, TR-069, ONVIF, HL7, FHIR, HIPAA,
     CDISC, XMPP XEP, ISO 20022, SWIFT, FixML, XBRL, OTA, NDC, AWS, EWS, WCF,
     and more. Integrates seamlessly with Apache, IIS, cURL, and WinInet.
  doc_url: https://www.genivia.com/docs.html
  dev_url: https://www.genivia.com/dev.html

extra:
  recipe-maintainers:
    - chrisburr
