{% set name = "gsoap" %}
{% set version = "2.7.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/gsoap2/gsoap-{{ version.split('.')[0] }}.{{ version.split('.')[1] }}/gsoap_{{ version }}.zip
  sha256: 88f317fac843b29c1a1332c02a25b64b7dfd93ac9bfa093c3b0eb0dc0c9aadf3
  patches:
    - patches/gsoap-ipv6.patch
    - patches/gsoap-iostream.patch
    - patches/gsoap-openssl.patch
    - patches/gsoap-pad.patch
    - 0001-Avoid-using-entire-std-namespace.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - bison
    - flex
    - gawk  # [unix]
    - make
    - libtool
    - sed
  host:
    - openssl
    - zlib

test:
  commands:
    - soapcpp2 -h

about:
  home: https://www.genivia.com/
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: 'The most advanced C/C++ autocoding tools for XML Web service APIs and other XML applications'

  description: |
     gSOAP is the top-rated agile development framework for C/C++ Web service
     APIs and XML. Join our rapidly growing world-wide customer base with
     over a million downloads. Start expediting the development of your
     products to meet the latest industry standards for XML, XML Web services,
     WSDL and SOAP, REST, JSON, WS-Security, WS-Trust with SAML,
     WS-ReliableMessaging, WS-Discovery, TR-069, ONVIF, HL7, FHIR, HIPAA,
     CDISC, XMPP XEP, ISO 20022, SWIFT, FixML, XBRL, OTA, NDC, AWS, EWS, WCF,
     and more. Integrates seamlessly with Apache, IIS, cURL, and WinInet.
  doc_url: https://www.genivia.com/docs.html
  dev_url: https://www.genivia.com/dev.html

extra:
  recipe-maintainers:
    - chrisburr
