appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: ABNBUb3CWB6U0sXqB0wCT5he5xUbQwyU4NR7E08qwxXzlCGDqXICBoftRtW9WlhxPeFgPsdT0lekebxyMAHJKJLsK6YMPe57zBVRsWTNCvPZxokcE397pom0bI8gidR3uyAfoba0h3dwfdj3oSMaDY5WH+bo6aOL3a7qlhpT8C2xY6AwFbmKnC9Un1qJ+pRoT/EuyZ7rzDAAAZANE8yZdEQLKeeXzExTHPy1Ubh+iC6FxqyIcv6qoqV5To8Vi7b5ajrNlP/v08nG3WyP7qYA2SlZTOuyj4Jf5yaeDvBOo8Ii5Ah4rDZFGGipNjO1u4o6gOKZk6NDnSTzP1GgvUgSp/lWXQhnWHykkOEJdangcqyIll60poTCmQUBhtKwBMonIyhpbCgVvTg8OcXPYmnGbempFS8QT8aP1+1pt39mY1PfSgwxKI+FJLsKy9s9QMAJndbBkQlXvntYpvIYO+mBs27BnS5kM92eQb6M0cUEPQTxy/KZtrBm6NmAHe4naIjaOp3Ukap33fxv0vJxyOocMFoP1uVhWzd34FLoxvOGKCB31PELb6PDLYvOlGaX3mXEJ43nMOpjF58OEtJeFBBKkuMjWmHOFNCM0j4fko3B/EfwHMOEd7irzxagb5oJFOFJCmRrjMcFpfdwbd3t0++5smPD2jWhEqztc0P7fbh+r48=}
conda_forge_output_validation: true
bot:
  automerge: true
